# Generated by Django 4.1.3 on 2022-12-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_alter_artist_image'),
        ('music', '0003_alter_album_cover'),
        ('account', '0003_alter_account_profile_image_alter_playlist_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='artists',
            field=models.ManyToManyField(blank=True, to='artist.artist'),
        ),
        migrations.AddField(
            model_name='account',
            name='songs',
            field=models.ManyToManyField(blank=True, null=True, to='music.song'),
        ),
    ]
