# Generated by Django 4.1.3 on 2022-12-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_album_cover'),
        ('account', '0004_account_artists_account_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='songs',
            field=models.ManyToManyField(blank=True, to='music.song'),
        ),
    ]
